apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: logis-api
  description: The Logis API
  tags:
    - python
    - flask
  annotations:
    # The annotation is deprecated, we use placeholders (see below) instead, remove it later.
    backstage.io/definition-at-location: 'url:http://0.0.0.0:8080/docs'
spec:
  type: openapi
  lifecycle: production
  owner: Tech Foundation Team
  system: logis
  dependsOn: ['resource:logis-meta-db']
  definition:
    $text: https://github.com/APIs-guru/openapi-directory/blob/main/APIs/archive.org/search/1.0.0/openapi.yaml